@HostAddress = http://localhost:5016

GET {{HostAddress}}/config?type=1
Accept: application/json

###

GET {{HostAddress}}/config?type=2
Accept: application/json

###

GET {{HostAddress}}/config?type=3
Accept: application/json

###